<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>305a0fd7-4693-4d28-9717-2994a867ad04</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.16.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\QNotificationService.Application\QNotificationService.Application\QNotificationService.Application.csproj" />
      <ProjectReference Include="..\..\QNotificationService.Infrastructure\QNotificationService.Infrastructure\QNotificationService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
